<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>KidsPocket.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KidsPocket.Application\KidsPocket.Application.csproj" />
    <ProjectReference Include="..\KidsPocket.Contracts\KidsPocket.Contracts.csproj" />
  </ItemGroup>

</Project>
